/* ============================================
   CONFIGURATION
   ============================================ */
const CONFIG = {
  SUPABASE_URL: 'https://sgiziayjfcjcgktytxmo.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnaXppYXlqZmNqY2drdHl0eG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2MjYxNzcsImV4cCI6MjA5ODIwMjE3N30.zZcMygvlMxLHPoDfUy9M7e1hirybwC-HIRAreh7XZHY',
  DEFAULT_COMMISSION_RATE: 0.12,
  MAX_QUOTES_PER_ORDER: 8,
  QUOTE_EXPIRY_HOURS: 24,
  PAGE_SIZE: 20,
  DISPATCH_CAP: 20,
  BAYESIAN_C: 10,
  BAYESIAN_M: 4.0,
  MIN_PAYOUT: 10,
  SUPPORTED_COUNTRIES: {
    SA: { currency: 'SAR', vat: 0.15, iban_len: 24, name_en: 'Saudi Arabia', name_ar: 'السعودية', name_no: 'Saudi-Arabia', name_sv: 'Saudiarabien' },
    AE: { currency: 'AED', vat: 0.05, iban_len: 23, name_en: 'UAE', name_ar: 'الإمارات', name_no: 'UAE', name_sv: 'UAE' },
    KW: { currency: 'KWD', vat: 0, iban_len: 30, name_en: 'Kuwait', name_ar: 'الكويت', name_no: 'Kuwait', name_sv: 'Kuwait' },
    QA: { currency: 'QAR', vat: 0, iban_len: 29, name_en: 'Qatar', name_ar: 'قطر', name_no: 'Qatar', name_sv: 'Qatar' },
    BH: { currency: 'BHD', vat: 0, iban_len: 22, name_en: 'Bahrain', name_ar: 'البحرين', name_no: 'Bahrain', name_sv: 'Bahrain' },
    OM: { currency: 'OMR', vat: 0, iban_len: 23, name_en: 'Oman', name_ar: 'عُمان', name_no: 'Oman', name_sv: 'Oman' },
    EG: { currency: 'EGP', vat: 0.14, iban_len: 29, name_en: 'Egypt', name_ar: 'مصر', name_no: 'Egypt', name_sv: 'Egypten' },
    NO: { currency: 'NOK', vat: 0.25, iban_len: 15, name_en: 'Norway', name_ar: 'النرويج', name_no: 'Norge', name_sv: 'Norge' },
    SE: { currency: 'SEK', vat: 0.25, iban_len: 22, name_en: 'Sweden', name_ar: 'السويد', name_no: 'Sverige', name_sv: 'Sverige' }
  },
  SUBSCRIPTION_PLANS: {
    pro_monthly: { tier: 'pro', period: 'monthly', price: 49 },
    pro_yearly: { tier: 'pro', period: 'yearly', price: 490 },
    business_monthly: { tier: 'business', period: 'monthly', price: 149 },
    business_yearly: { tier: 'business', period: 'yearly', price: 1490 }
  },
  BOOST_PLANS: {
    7: { price: 19 },
    14: { price: 35 },
    30: { price: 69 }
  }
};

/* ============================================
   I18N — TRANSLATIONS
   ============================================ */
const I18N = {
  en: {
    dir: 'ltr',
    // Auth
    welcome_back: 'Welcome back',
    email: 'Email',
    password: 'Password',
    login: 'Log in',
    forgot_password: 'Forgot password?',
    no_account: "Don't have an account?",
    sign_up: 'Sign up',
    full_name: 'Full name',
    confirm_password: 'Confirm password',
    create_account: 'Create account',
    looking_for_service: 'Looking for a service',
    offering_service: 'Offering a service',
    agree_terms: 'I agree to the Terms & Conditions',
    verify_phone: 'Verify your phone',
    enter_otp: 'Enter the 6-digit code sent to your phone',
    resend_in: 'Resend in',
    resend_code: 'Resend code',
    reset_password: 'Reset password',
    send_reset_link: 'Send reset link',
    reset_sent: 'Reset link sent to your email',
    phone: 'Phone number',
    phone_login: 'Phone login',
    email_login: 'Email login',
    or: 'or',
    // Navigation
    home: 'Home',
    my_orders: 'My Orders',
    explore: 'Explore',
    profile: 'Profile',
    dashboard: 'Dashboard',
    earnings: 'Earnings',
    // Home
    hello: 'Hello',
    search_services: 'Search services...',
    recent_orders: 'Recent Orders',
    view_all: 'View all',
    // Orders
    all: 'All',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    no_orders: 'No orders yet',
    no_orders_desc: 'Your orders will appear here',
    // Order statuses
    status_pending: 'Pending',
    status_quoted: 'Quoted',
    status_confirmed: 'Confirmed',
    status_payment_pending: 'Payment Pending',
    status_in_progress: 'In Progress',
    status_completed: 'Completed',
    status_closed: 'Closed',
    status_cancelled: 'Cancelled',
    status_disputed: 'Disputed',
    // Create order
    new_order: 'New Order',
    order_title: 'Title',
    order_title_ph: 'e.g. Fix kitchen faucet',
    description: 'Description',
    description_ph: 'Describe the service you need in detail...',
    location: 'Location',
    pick_location: 'Pick on map',
    use_my_location: 'Use my location',
    budget: 'Budget (optional)',
    photos: 'Photos (optional)',
    add_photo: 'Add photo',
    submit_order: 'Submit Order',
    // Order detail
    order_details: 'Order Details',
    quotes: 'Quotes',
    no_quotes: 'No quotes yet',
    waiting_quotes: 'Waiting for provider quotes...',
    accept: 'Accept',
    reject: 'Reject',
    open_chat: 'Open Chat',
    rate_service: 'Rate Service',
    open_dispute: 'Open Dispute',
    cancel_order: 'Cancel Order',
    pay_now: 'Pay Now',
    mark_complete: 'Mark Complete',
    confirm_completion: 'Confirm Completion',
    // Chat
    type_message: 'Type a message...',
    // Payment
    payment: 'Payment',
    select_method: 'Select payment method',
    card: 'Credit/Debit Card',
    apple_pay: 'Apple Pay',
    mada: 'Mada',
    stc_pay: 'STC Pay',
    cash: 'Cash',
    vipps: 'Vipps',
    swish: 'Swish',
    subtotal: 'Subtotal',
    vat: 'VAT',
    total: 'Total',
    // Review
    rate_provider: 'Rate your provider',
    leave_comment: 'Leave a comment (optional)...',
    submit_review: 'Submit Review',
    // Provider
    available: 'Available',
    unavailable: 'Unavailable',
    pending_quotes: 'Pending Quotes',
    active_jobs: 'Active Jobs',
    earned_today: 'Earned Today',
    incoming_requests: 'Incoming Requests',
    submit_quote: 'Submit Quote',
    your_price: 'Your price',
    estimated_hours: 'Estimated hours',
    notes: 'Notes',
    notes_ph: 'Notes for the customer...',
    send_quote: 'Send Quote',
    my_quotes: 'My Quotes',
    total_balance: 'Total Balance',
    available_balance: 'Available',
    pending_balance: 'Pending',
    request_payout: 'Request Payout',
    // KYC
    kyc_title: 'Identity Verification',
    kyc_not_submitted: 'Please submit your documents to get verified',
    kyc_pending: 'Your documents are under review',
    kyc_approved: 'Your identity has been verified',
    kyc_rejected: 'Your documents were rejected',
    national_id_front: 'National ID (Front)',
    national_id_back: 'National ID (Back)',
    trade_license: 'Trade License (optional)',
    submit_for_review: 'Submit for Review',
    upload: 'Upload',
    // Profile
    edit_profile: 'Edit Profile',
    notifications: 'Notifications',
    payment_wallet: 'Payment & Wallet',
    security: 'Security',
    export_data: 'Export My Data',
    delete_account: 'Delete Account',
    logout: 'Log out',
    language: 'Language',
    app_version: 'Version',
    save: 'Save',
    // Provider profile
    bio: 'Bio',
    service_categories: 'Service Categories',
    hourly_rate: 'Hourly Rate',
    iban: 'IBAN',
    subscription: 'Subscription',
    boost: 'Boost',
    upgrade_to_pro: 'Upgrade to Pro',
    response_time: 'Usually responds in',
    minutes: 'minutes',
    reviews_count: 'reviews',
    // Admin
    admin_panel: 'Admin Panel',
    total_users: 'Total Users',
    active_orders: 'Active Orders',
    pending_kyc: 'Pending KYC',
    open_disputes: 'Open Disputes',
    users: 'Users',
    disputes: 'Disputes',
    reports: 'Reports',
    search_users: 'Search users...',
    customer: 'Customer',
    provider: 'Provider',
    admin: 'Admin',
    superadmin: 'Super Admin',
    banned: 'Banned',
    ban_user: 'Ban User',
    unban_user: 'Unban User',
    ban_reason: 'Ban reason',
    // Disputes
    open: 'Open',
    investigating: 'Investigating',
    resolved: 'Resolved',
    customer_favor: 'Customer Favor',
    provider_favor: 'Provider Favor',
    settlement: 'Settlement',
    resolve: 'Resolve',
    admin_note: 'Admin note',
    // Reports
    revenue: 'Revenue',
    commission: 'Commission',
    total_orders_label: 'Total Orders',
    avg_order_value: 'Avg. Order Value',
    this_month: 'This Month',
    last_month: 'Last Month',
    three_months: '3 Months',
    this_year: 'This Year',
    from_date: 'From',
    to_date: 'To',
    // General
    loading: 'Loading...',
    error_occurred: 'An error occurred',
    retry: 'Retry',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    more: 'More',
    less: 'Less',
    ago: 'ago',
    today: 'Today',
    yesterday: 'Yesterday',
    install_app: 'Install App',
    // Phone verify
    otp_title: 'Verify Phone',
    otp_subtitle: 'Enter the 6-digit code sent to',
    otp_resend: 'Resend code',
    otp_resend_in: 'Resend in',
    otp_error: 'Invalid code, please try again',
    // Subscription
    subscription_title: 'Subscription Plans',
    free_tier: 'Free',
    pro_tier: 'Pro',
    business_tier: 'Business',
    monthly: 'Monthly',
    yearly: 'Yearly',
    current_plan: 'Current Plan',
    subscribe: 'Subscribe',
    plan_feature_visibility: 'Boosted visibility',
    plan_feature_priority: 'Priority dispatch',
    plan_feature_analytics: 'Analytics dashboard',
    plan_feature_agency: 'Agency model',
    plan_feature_basic: 'Basic listing',
    plan_feature_standard: 'Standard dispatch',
    save_percent: 'Save',
    // Boost
    boost_title: 'Boost Visibility',
    boost_desc: 'Appear higher in search results',
    boost_active: 'Boost Active',
    boost_expires: 'Expires',
    boost_multiplier: '1.2x visibility multiplier',
    days: 'days',
    buy_boost: 'Buy Boost',
    // Provider detail
    provider_detail: 'Provider Profile',
    completed_jobs: 'Completed Jobs',
    request_service: 'Request Service',
    member_since: 'Member since',
    // Audit logs
    audit_logs: 'Audit Logs',
    no_logs: 'No audit logs found',
    // Notifications
    notif_enable: 'Enable push notifications',
    notif_orders: 'Order updates',
    notif_chat: 'Chat messages',
    notif_promo: 'Promotions',
    // Upload
    uploading: 'Uploading...',
    upload_success: 'Upload successful',
    upload_error: 'Upload failed',
    // Dispatch
    dispatch_score: 'Dispatch Score',
    // OSRM
    walking: 'Walking',
    driving: 'Driving',
    distance: 'Distance',
    duration: 'Duration',
    km: 'km',
    min: 'min',
    // Payment flow
    commission_fee: 'Platform fee',
    processing: 'Processing payment...',
    payment_success: 'Payment successful',
    payment_failed: 'Payment failed',
    escrow_held: 'Funds held in escrow',
    // Data export & deletion
    export_requested: 'Data export requested. You will receive a download link.',
    delete_warning: 'This action cannot be undone. Your data will be deleted after 30 days.',
    delete_confirm: 'Type DELETE to confirm',
    account_deletion: 'Account Deletion'
  },
  ar: {
    dir: 'rtl',
    welcome_back: 'مرحبًا بعودتك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    login: 'تسجيل الدخول',
    forgot_password: 'نسيت كلمة المرور؟',
    no_account: 'ليس لديك حساب؟',
    sign_up: 'سجّل الآن',
    full_name: 'الاسم الكامل',
    confirm_password: 'تأكيد كلمة المرور',
    create_account: 'إنشاء حساب',
    looking_for_service: 'أبحث عن خدمة',
    offering_service: 'أقدم خدمة',
    agree_terms: 'أوافق على الشروط والأحكام',
    verify_phone: 'تحقق من هاتفك',
    enter_otp: 'أدخل الرمز المكون من 6 أرقام المرسل إلى هاتفك',
    resend_in: 'إعادة الإرسال خلال',
    resend_code: 'إعادة إرسال الرمز',
    reset_password: 'إعادة تعيين كلمة المرور',
    send_reset_link: 'إرسال رابط الاستعادة',
    reset_sent: 'تم إرسال رابط الاستعادة إلى بريدك',
    phone: 'رقم الهاتف',
    phone_login: 'تسجيل بالهاتف',
    email_login: 'تسجيل بالبريد',
    or: 'أو',
    home: 'الرئيسية',
    my_orders: 'طلباتي',
    explore: 'استكشف',
    profile: 'حسابي',
    dashboard: 'لوحة التحكم',
    earnings: 'الأرباح',
    hello: 'مرحباً',
    search_services: 'ابحث عن خدمات...',
    recent_orders: 'طلباتك الأخيرة',
    view_all: 'اعرض الكل',
    all: 'الكل',
    active: 'جارية',
    completed: 'مكتملة',
    cancelled: 'ملغية',
    no_orders: 'لا توجد طلبات',
    no_orders_desc: 'ستظهر طلباتك هنا',
    status_pending: 'قيد الانتظار',
    status_quoted: 'تم التسعير',
    status_confirmed: 'مؤكد',
    status_payment_pending: 'في انتظار الدفع',
    status_in_progress: 'جاري التنفيذ',
    status_completed: 'مكتمل',
    status_closed: 'مغلق',
    status_cancelled: 'ملغي',
    status_disputed: 'متنازع عليه',
    new_order: 'طلب جديد',
    order_title: 'العنوان',
    order_title_ph: 'مثال: إصلاح صنبور المطبخ',
    description: 'الوصف',
    description_ph: 'صف الخدمة التي تحتاجها بالتفصيل...',
    location: 'الموقع',
    pick_location: 'اختر على الخريطة',
    use_my_location: 'استخدم موقعي',
    budget: 'الميزانية (اختياري)',
    photos: 'صور (اختياري)',
    add_photo: 'إضافة صورة',
    submit_order: 'إرسال الطلب',
    order_details: 'تفاصيل الطلب',
    quotes: 'العروض',
    no_quotes: 'لا توجد عروض',
    waiting_quotes: 'في انتظار عروض المزودين...',
    accept: 'قبول',
    reject: 'رفض',
    open_chat: 'فتح محادثة',
    rate_service: 'تقييم الخدمة',
    open_dispute: 'فتح نزاع',
    cancel_order: 'إلغاء الطلب',
    pay_now: 'ادفع الآن',
    mark_complete: 'إتمام العمل',
    confirm_completion: 'تأكيد الإتمام',
    type_message: 'اكتب رسالة...',
    payment: 'الدفع',
    select_method: 'اختر طريقة الدفع',
    card: 'بطاقة ائتمان/خصم',
    apple_pay: 'Apple Pay',
    mada: 'مدى',
    stc_pay: 'STC Pay',
    cash: 'نقداً',
    vipps: 'Vipps',
    swish: 'Swish',
    subtotal: 'المبلغ الفرعي',
    vat: 'ضريبة القيمة المضافة',
    total: 'الإجمالي',
    rate_provider: 'قيّم مزود الخدمة',
    leave_comment: 'اترك تعليقاً (اختياري)...',
    submit_review: 'إرسال التقييم',
    available: 'متاح',
    unavailable: 'غير متاح',
    pending_quotes: 'عروض قيد الانتظار',
    active_jobs: 'مهام نشطة',
    earned_today: 'أرباح اليوم',
    incoming_requests: 'طلبات واردة',
    submit_quote: 'إرسال عرض سعر',
    your_price: 'سعرك',
    estimated_hours: 'الساعات التقديرية',
    notes: 'ملاحظات',
    notes_ph: 'ملاحظات للعميل...',
    send_quote: 'إرسال العرض',
    my_quotes: 'عروضي',
    total_balance: 'الرصيد الإجمالي',
    available_balance: 'متاح',
    pending_balance: 'معلّق',
    request_payout: 'طلب سحب',
    kyc_title: 'التحقق من الهوية',
    kyc_not_submitted: 'يرجى إرسال مستنداتك للتحقق',
    kyc_pending: 'مستنداتك قيد المراجعة',
    kyc_approved: 'تم التحقق من هويتك',
    kyc_rejected: 'تم رفض مستنداتك',
    national_id_front: 'الهوية الوطنية (أمام)',
    national_id_back: 'الهوية الوطنية (خلف)',
    trade_license: 'الرخصة التجارية (اختياري)',
    submit_for_review: 'إرسال للمراجعة',
    upload: 'رفع',
    edit_profile: 'تعديل الملف الشخصي',
    notifications: 'الإشعارات',
    payment_wallet: 'الدفع والمحفظة',
    security: 'الأمان',
    export_data: 'تصدير بياناتي',
    delete_account: 'حذف الحساب',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    app_version: 'الإصدار',
    save: 'حفظ',
    bio: 'نبذة',
    service_categories: 'فئات الخدمة',
    hourly_rate: 'سعر الساعة',
    iban: 'الآيبان',
    subscription: 'الاشتراك',
    boost: 'تعزيز',
    upgrade_to_pro: 'ترقية إلى Pro',
    response_time: 'عادةً يرد خلال',
    minutes: 'دقيقة',
    reviews_count: 'تقييم',
    admin_panel: 'لوحة الإدارة',
    total_users: 'إجمالي المستخدمين',
    active_orders: 'طلبات نشطة',
    pending_kyc: 'تحقق معلّق',
    open_disputes: 'نزاعات مفتوحة',
    users: 'المستخدمون',
    disputes: 'النزاعات',
    reports: 'التقارير',
    search_users: 'بحث عن مستخدمين...',
    customer: 'عميل',
    provider: 'مزوّد',
    admin: 'مشرف',
    superadmin: 'مشرف عام',
    banned: 'محظور',
    ban_user: 'حظر المستخدم',
    unban_user: 'رفع الحظر',
    ban_reason: 'سبب الحظر',
    open: 'مفتوحة',
    investigating: 'جارية',
    resolved: 'محلولة',
    customer_favor: 'لصالح العميل',
    provider_favor: 'لصالح المزوّد',
    settlement: 'تسوية',
    resolve: 'حل',
    admin_note: 'ملاحظة المشرف',
    revenue: 'الإيرادات',
    commission: 'العمولة',
    total_orders_label: 'إجمالي الطلبات',
    avg_order_value: 'متوسط قيمة الطلب',
    this_month: 'هذا الشهر',
    last_month: 'الشهر الماضي',
    three_months: '3 أشهر',
    this_year: 'هذه السنة',
    from_date: 'من',
    to_date: 'إلى',
    loading: 'جاري التحميل...',
    error_occurred: 'حدث خطأ',
    retry: 'إعادة المحاولة',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    close: 'إغلاق',
    back: 'رجوع',
    done: 'تم',
    yes: 'نعم',
    no: 'لا',
    ok: 'حسناً',
    search: 'بحث',
    filter: 'تصفية',
    sort: 'ترتيب',
    more: 'المزيد',
    less: 'أقل',
    ago: 'مضت',
    today: 'اليوم',
    yesterday: 'أمس',
    install_app: 'تثبيت التطبيق',
    otp_title: 'تحقق من الهاتف',
    otp_subtitle: 'أدخل الرمز المكون من 6 أرقام المرسل إلى',
    otp_resend: 'إعادة إرسال الرمز',
    otp_resend_in: 'إعادة الإرسال خلال',
    otp_error: 'رمز غير صالح، حاول مجدداً',
    subscription_title: 'خطط الاشتراك',
    free_tier: 'مجاني',
    pro_tier: 'برو',
    business_tier: 'أعمال',
    monthly: 'شهري',
    yearly: 'سنوي',
    current_plan: 'الخطة الحالية',
    subscribe: 'اشترك',
    plan_feature_visibility: 'ظهور معزز',
    plan_feature_priority: 'أولوية في التوزيع',
    plan_feature_analytics: 'لوحة تحليلات',
    plan_feature_agency: 'نموذج وكالة',
    plan_feature_basic: 'قائمة أساسية',
    plan_feature_standard: 'توزيع قياسي',
    save_percent: 'وفّر',
    boost_title: 'تعزيز الظهور',
    boost_desc: 'اظهر أعلى في نتائج البحث',
    boost_active: 'التعزيز نشط',
    boost_expires: 'ينتهي',
    boost_multiplier: 'مضاعف ظهور 1.2×',
    days: 'أيام',
    buy_boost: 'شراء تعزيز',
    provider_detail: 'ملف المزوّد',
    completed_jobs: 'مهام مكتملة',
    request_service: 'طلب خدمة',
    member_since: 'عضو منذ',
    audit_logs: 'سجل العمليات',
    no_logs: 'لا توجد سجلات',
    notif_enable: 'تفعيل إشعارات الدفع',
    notif_orders: 'تحديثات الطلبات',
    notif_chat: 'رسائل المحادثة',
    notif_promo: 'العروض الترويجية',
    uploading: 'جاري الرفع...',
    upload_success: 'تم الرفع بنجاح',
    upload_error: 'فشل الرفع',
    dispatch_score: 'نقاط التوزيع',
    walking: 'مشي',
    driving: 'سيارة',
    distance: 'المسافة',
    duration: 'المدة',
    km: 'كم',
    min: 'دقيقة',
    commission_fee: 'رسوم المنصة',
    processing: 'جاري معالجة الدفع...',
    payment_success: 'تم الدفع بنجاح',
    payment_failed: 'فشل الدفع',
    escrow_held: 'الأموال محتجزة في الضمان',
    export_requested: 'تم طلب تصدير البيانات. ستتلقى رابط تحميل.',
    delete_warning: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف بياناتك بعد 30 يوماً.',
    delete_confirm: 'اكتب DELETE للتأكيد',
    account_deletion: 'حذف الحساب'
  },
  no: {
    dir: 'ltr',
    welcome_back: 'Velkommen tilbake',
    email: 'E-post',
    password: 'Passord',
    login: 'Logg inn',
    forgot_password: 'Glemt passord?',
    no_account: 'Har du ikke en konto?',
    sign_up: 'Registrer deg',
    full_name: 'Fullt navn',
    confirm_password: 'Bekreft passord',
    create_account: 'Opprett konto',
    looking_for_service: 'Ser etter en tjeneste',
    offering_service: 'Tilbyr en tjeneste',
    agree_terms: 'Jeg godtar vilkårene',
    verify_phone: 'Bekreft telefonen din',
    enter_otp: 'Skriv inn 6-sifret kode sendt til telefonen din',
    resend_in: 'Send på nytt om',
    resend_code: 'Send kode på nytt',
    reset_password: 'Tilbakestill passord',
    send_reset_link: 'Send tilbakestillingslenke',
    reset_sent: 'Tilbakestillingslenke sendt til e-posten din',
    phone: 'Telefonnummer',
    phone_login: 'Telefoninnlogging',
    email_login: 'E-postinnlogging',
    or: 'eller',
    home: 'Hjem',
    my_orders: 'Mine bestillinger',
    explore: 'Utforsk',
    profile: 'Profil',
    dashboard: 'Dashbord',
    earnings: 'Inntekter',
    hello: 'Hei',
    search_services: 'Søk etter tjenester...',
    recent_orders: 'Nylige bestillinger',
    view_all: 'Vis alle',
    all: 'Alle',
    active: 'Aktive',
    completed: 'Fullført',
    cancelled: 'Avbrutt',
    no_orders: 'Ingen bestillinger ennå',
    no_orders_desc: 'Bestillingene dine vises her',
    status_pending: 'Venter',
    status_quoted: 'Tilbudt',
    status_confirmed: 'Bekreftet',
    status_payment_pending: 'Venter på betaling',
    status_in_progress: 'Pågår',
    status_completed: 'Fullført',
    status_closed: 'Lukket',
    status_cancelled: 'Avbrutt',
    status_disputed: 'Omstridt',
    new_order: 'Ny bestilling',
    order_title: 'Tittel',
    order_title_ph: 'F.eks. Fiks kjøkkenkran',
    description: 'Beskrivelse',
    description_ph: 'Beskriv tjenesten du trenger i detalj...',
    location: 'Sted',
    pick_location: 'Velg på kart',
    use_my_location: 'Bruk min posisjon',
    budget: 'Budsjett (valgfritt)',
    photos: 'Bilder (valgfritt)',
    add_photo: 'Legg til bilde',
    submit_order: 'Send bestilling',
    order_details: 'Bestillingsdetaljer',
    quotes: 'Tilbud',
    no_quotes: 'Ingen tilbud ennå',
    waiting_quotes: 'Venter på tilbud fra leverandører...',
    accept: 'Godta',
    reject: 'Avvis',
    open_chat: 'Åpne chat',
    rate_service: 'Vurder tjenesten',
    open_dispute: 'Åpne tvist',
    cancel_order: 'Avbryt bestilling',
    pay_now: 'Betal nå',
    mark_complete: 'Merk som fullført',
    confirm_completion: 'Bekreft fullføring',
    type_message: 'Skriv en melding...',
    payment: 'Betaling',
    select_method: 'Velg betalingsmetode',
    card: 'Kreditt-/debetkort',
    apple_pay: 'Apple Pay',
    mada: 'Mada',
    stc_pay: 'STC Pay',
    cash: 'Kontant',
    vipps: 'Vipps',
    swish: 'Swish',
    subtotal: 'Delsum',
    vat: 'MVA',
    total: 'Totalt',
    rate_provider: 'Vurder leverandøren',
    leave_comment: 'Legg igjen en kommentar (valgfritt)...',
    submit_review: 'Send vurdering',
    available: 'Tilgjengelig',
    unavailable: 'Utilgjengelig',
    pending_quotes: 'Ventende tilbud',
    active_jobs: 'Aktive jobber',
    earned_today: 'Tjent i dag',
    incoming_requests: 'Innkommende forespørsler',
    submit_quote: 'Send tilbud',
    your_price: 'Din pris',
    estimated_hours: 'Estimerte timer',
    notes: 'Notater',
    notes_ph: 'Notater til kunden...',
    send_quote: 'Send tilbud',
    my_quotes: 'Mine tilbud',
    total_balance: 'Total saldo',
    available_balance: 'Tilgjengelig',
    pending_balance: 'Ventende',
    request_payout: 'Be om utbetaling',
    kyc_title: 'Identitetsverifisering',
    kyc_not_submitted: 'Vennligst send inn dokumentene dine for verifisering',
    kyc_pending: 'Dokumentene dine er under gjennomgang',
    kyc_approved: 'Identiteten din er verifisert',
    kyc_rejected: 'Dokumentene dine ble avvist',
    national_id_front: 'Nasjonal ID (forside)',
    national_id_back: 'Nasjonal ID (bakside)',
    trade_license: 'Næringslisens (valgfritt)',
    submit_for_review: 'Send til gjennomgang',
    upload: 'Last opp',
    edit_profile: 'Rediger profil',
    notifications: 'Varsler',
    payment_wallet: 'Betaling og lommebok',
    security: 'Sikkerhet',
    export_data: 'Eksporter mine data',
    delete_account: 'Slett konto',
    logout: 'Logg ut',
    language: 'Språk',
    app_version: 'Versjon',
    save: 'Lagre',
    bio: 'Bio',
    service_categories: 'Tjenestekategorier',
    hourly_rate: 'Timepris',
    iban: 'IBAN',
    subscription: 'Abonnement',
    boost: 'Boost',
    upgrade_to_pro: 'Oppgrader til Pro',
    response_time: 'Svarer vanligvis innen',
    minutes: 'minutter',
    reviews_count: 'vurderinger',
    admin_panel: 'Adminpanel',
    total_users: 'Totalt brukere',
    active_orders: 'Aktive bestillinger',
    pending_kyc: 'Ventende KYC',
    open_disputes: 'Åpne tvister',
    users: 'Brukere',
    disputes: 'Tvister',
    reports: 'Rapporter',
    search_users: 'Søk brukere...',
    customer: 'Kunde',
    provider: 'Leverandør',
    admin: 'Admin',
    superadmin: 'Superadmin',
    banned: 'Utestengt',
    ban_user: 'Utesteng bruker',
    unban_user: 'Opphev utestenging',
    ban_reason: 'Grunn for utestenging',
    open: 'Åpne',
    investigating: 'Under etterforskning',
    resolved: 'Løst',
    customer_favor: 'Kundens favør',
    provider_favor: 'Leverandørens favør',
    settlement: 'Forlik',
    resolve: 'Løs',
    admin_note: 'Adminnotat',
    revenue: 'Inntekter',
    commission: 'Provisjon',
    total_orders_label: 'Totale bestillinger',
    avg_order_value: 'Gj.snitt bestillingsverdi',
    this_month: 'Denne måneden',
    last_month: 'Forrige måned',
    three_months: '3 måneder',
    this_year: 'I år',
    from_date: 'Fra',
    to_date: 'Til',
    loading: 'Laster...',
    error_occurred: 'En feil oppstod',
    retry: 'Prøv igjen',
    confirm: 'Bekreft',
    cancel: 'Avbryt',
    close: 'Lukk',
    back: 'Tilbake',
    done: 'Ferdig',
    yes: 'Ja',
    no: 'Nei',
    ok: 'OK',
    search: 'Søk',
    filter: 'Filter',
    sort: 'Sorter',
    more: 'Mer',
    less: 'Mindre',
    ago: 'siden',
    today: 'I dag',
    yesterday: 'I går',
    install_app: 'Installer app',
    otp_title: 'Bekreft telefon',
    otp_subtitle: 'Skriv inn 6-sifret kode sendt til',
    otp_resend: 'Send kode på nytt',
    otp_resend_in: 'Send på nytt om',
    otp_error: 'Ugyldig kode, prøv igjen',
    subscription_title: 'Abonnementsplaner',
    free_tier: 'Gratis',
    pro_tier: 'Pro',
    business_tier: 'Business',
    monthly: 'Månedlig',
    yearly: 'Årlig',
    current_plan: 'Nåværende plan',
    subscribe: 'Abonner',
    plan_feature_visibility: 'Økt synlighet',
    plan_feature_priority: 'Prioritert utsendelse',
    plan_feature_analytics: 'Analysepanel',
    plan_feature_agency: 'Byråmodell',
    plan_feature_basic: 'Grunnleggende oppføring',
    plan_feature_standard: 'Standard utsendelse',
    save_percent: 'Spar',
    boost_title: 'Boost synlighet',
    boost_desc: 'Vis høyere i søkeresultater',
    boost_active: 'Boost aktiv',
    boost_expires: 'Utløper',
    boost_multiplier: '1.2x synlighetsmultiplikator',
    days: 'dager',
    buy_boost: 'Kjøp boost',
    provider_detail: 'Leverandørprofil',
    completed_jobs: 'Fullførte jobber',
    request_service: 'Be om tjeneste',
    member_since: 'Medlem siden',
    audit_logs: 'Revisjonslogger',
    no_logs: 'Ingen logger funnet',
    notif_enable: 'Aktiver push-varsler',
    notif_orders: 'Bestillingsoppdateringer',
    notif_chat: 'Chatmeldinger',
    notif_promo: 'Kampanjer',
    uploading: 'Laster opp...',
    upload_success: 'Opplasting vellykket',
    upload_error: 'Opplasting mislyktes',
    dispatch_score: 'Utsendelsespoeng',
    walking: 'Gange',
    driving: 'Kjøring',
    distance: 'Avstand',
    duration: 'Varighet',
    km: 'km',
    min: 'min',
    commission_fee: 'Plattformgebyr',
    processing: 'Behandler betaling...',
    payment_success: 'Betaling vellykket',
    payment_failed: 'Betaling mislyktes',
    escrow_held: 'Midler holdt i escrow',
    export_requested: 'Dataeksport forespurt. Du vil motta en nedlastingslenke.',
    delete_warning: 'Denne handlingen kan ikke angres. Dataene dine slettes etter 30 dager.',
    delete_confirm: 'Skriv DELETE for å bekrefte',
    account_deletion: 'Slett konto'
  },
  sv: {
    dir: 'ltr',
    welcome_back: 'Välkommen tillbaka',
    email: 'E-post',
    password: 'Lösenord',
    login: 'Logga in',
    forgot_password: 'Glömt lösenord?',
    no_account: 'Har du inget konto?',
    sign_up: 'Registrera dig',
    full_name: 'Fullständigt namn',
    confirm_password: 'Bekräfta lösenord',
    create_account: 'Skapa konto',
    looking_for_service: 'Letar efter en tjänst',
    offering_service: 'Erbjuder en tjänst',
    agree_terms: 'Jag godkänner villkoren',
    verify_phone: 'Verifiera din telefon',
    enter_otp: 'Ange den 6-siffriga koden som skickats till din telefon',
    resend_in: 'Skicka igen om',
    resend_code: 'Skicka kod igen',
    reset_password: 'Återställ lösenord',
    send_reset_link: 'Skicka återställningslänk',
    reset_sent: 'Återställningslänk skickad till din e-post',
    phone: 'Telefonnummer',
    phone_login: 'Telefoninloggning',
    email_login: 'E-postinloggning',
    or: 'eller',
    home: 'Hem',
    my_orders: 'Mina beställningar',
    explore: 'Utforska',
    profile: 'Profil',
    dashboard: 'Instrumentpanel',
    earnings: 'Intäkter',
    hello: 'Hej',
    search_services: 'Sök tjänster...',
    recent_orders: 'Senaste beställningar',
    view_all: 'Visa alla',
    all: 'Alla',
    active: 'Aktiva',
    completed: 'Slutförda',
    cancelled: 'Avbrutna',
    no_orders: 'Inga beställningar ännu',
    no_orders_desc: 'Dina beställningar visas här',
    status_pending: 'Väntar',
    status_quoted: 'Offererad',
    status_confirmed: 'Bekräftad',
    status_payment_pending: 'Väntar på betalning',
    status_in_progress: 'Pågående',
    status_completed: 'Slutförd',
    status_closed: 'Stängd',
    status_cancelled: 'Avbruten',
    status_disputed: 'Omtvistad',
    new_order: 'Ny beställning',
    order_title: 'Titel',
    order_title_ph: 'T.ex. Fixa köks kran',
    description: 'Beskrivning',
    description_ph: 'Beskriv tjänsten du behöver i detalj...',
    location: 'Plats',
    pick_location: 'Välj på karta',
    use_my_location: 'Använd min plats',
    budget: 'Budget (valfritt)',
    photos: 'Bilder (valfritt)',
    add_photo: 'Lägg till bild',
    submit_order: 'Skicka beställning',
    order_details: 'Beställningsdetaljer',
    quotes: 'Offerter',
    no_quotes: 'Inga offerter ännu',
    waiting_quotes: 'Väntar på offerter från leverantörer...',
    accept: 'Acceptera',
    reject: 'Avvisa',
    open_chat: 'Öppna chatt',
    rate_service: 'Betygsätt tjänsten',
    open_dispute: 'Öppna tvist',
    cancel_order: 'Avbryt beställning',
    pay_now: 'Betala nu',
    mark_complete: 'Markera som klar',
    confirm_completion: 'Bekräfta slutförande',
    type_message: 'Skriv ett meddelande...',
    payment: 'Betalning',
    select_method: 'Välj betalningsmetod',
    card: 'Kredit-/betalkort',
    apple_pay: 'Apple Pay',
    mada: 'Mada',
    stc_pay: 'STC Pay',
    cash: 'Kontant',
    vipps: 'Vipps',
    swish: 'Swish',
    subtotal: 'Delsumma',
    vat: 'Moms',
    total: 'Totalt',
    rate_provider: 'Betygsätt leverantören',
    leave_comment: 'Lämna en kommentar (valfritt)...',
    submit_review: 'Skicka betyg',
    available: 'Tillgänglig',
    unavailable: 'Otillgänglig',
    pending_quotes: 'Väntande offerter',
    active_jobs: 'Aktiva jobb',
    earned_today: 'Tjänat idag',
    incoming_requests: 'Inkommande förfrågningar',
    submit_quote: 'Skicka offert',
    your_price: 'Ditt pris',
    estimated_hours: 'Uppskattade timmar',
    notes: 'Anteckningar',
    notes_ph: 'Anteckningar till kunden...',
    send_quote: 'Skicka offert',
    my_quotes: 'Mina offerter',
    total_balance: 'Totalt saldo',
    available_balance: 'Tillgängligt',
    pending_balance: 'Väntande',
    request_payout: 'Begär utbetalning',
    kyc_title: 'Identitetsverifiering',
    kyc_not_submitted: 'Vänligen skicka in dina dokument för verifiering',
    kyc_pending: 'Dina dokument granskas',
    kyc_approved: 'Din identitet har verifierats',
    kyc_rejected: 'Dina dokument avvisades',
    national_id_front: 'Nationellt ID (framsida)',
    national_id_back: 'Nationellt ID (baksida)',
    trade_license: 'Handelslicens (valfritt)',
    submit_for_review: 'Skicka för granskning',
    upload: 'Ladda upp',
    edit_profile: 'Redigera profil',
    notifications: 'Aviseringar',
    payment_wallet: 'Betalning & plånbok',
    security: 'Säkerhet',
    export_data: 'Exportera mina data',
    delete_account: 'Radera konto',
    logout: 'Logga ut',
    language: 'Språk',
    app_version: 'Version',
    save: 'Spara',
    bio: 'Bio',
    service_categories: 'Tjänstekategorier',
    hourly_rate: 'Timpris',
    iban: 'IBAN',
    subscription: 'Prenumeration',
    boost: 'Boost',
    upgrade_to_pro: 'Uppgradera till Pro',
    response_time: 'Svarar vanligtvis inom',
    minutes: 'minuter',
    reviews_count: 'omdömen',
    admin_panel: 'Adminpanel',
    total_users: 'Totala användare',
    active_orders: 'Aktiva beställningar',
    pending_kyc: 'Väntande KYC',
    open_disputes: 'Öppna tvister',
    users: 'Användare',
    disputes: 'Tvister',
    reports: 'Rapporter',
    search_users: 'Sök användare...',
    customer: 'Kund',
    provider: 'Leverantör',
    admin: 'Admin',
    superadmin: 'Superadmin',
    banned: 'Avstängd',
    ban_user: 'Stäng av användare',
    unban_user: 'Häv avstängning',
    ban_reason: 'Anledning för avstängning',
    open: 'Öppna',
    investigating: 'Under utredning',
    resolved: 'Löst',
    customer_favor: 'Kundens fördel',
    provider_favor: 'Leverantörens fördel',
    settlement: 'Förlikning',
    resolve: 'Lös',
    admin_note: 'Adminanteckning',
    revenue: 'Intäkter',
    commission: 'Provision',
    total_orders_label: 'Totala beställningar',
    avg_order_value: 'Gns. beställningsvärde',
    this_month: 'Denna månad',
    last_month: 'Förra månaden',
    three_months: '3 månader',
    this_year: 'I år',
    from_date: 'Från',
    to_date: 'Till',
    loading: 'Laddar...',
    error_occurred: 'Ett fel uppstod',
    retry: 'Försök igen',
    confirm: 'Bekräfta',
    cancel: 'Avbryt',
    close: 'Stäng',
    back: 'Tillbaka',
    done: 'Klar',
    yes: 'Ja',
    no: 'Nej',
    ok: 'OK',
    search: 'Sök',
    filter: 'Filtrera',
    sort: 'Sortera',
    more: 'Mer',
    less: 'Mindre',
    ago: 'sedan',
    today: 'Idag',
    yesterday: 'Igår',
    install_app: 'Installera app',
    otp_title: 'Verifiera telefon',
    otp_subtitle: 'Ange den 6-siffriga koden som skickats till',
    otp_resend: 'Skicka kod igen',
    otp_resend_in: 'Skicka igen om',
    otp_error: 'Ogiltig kod, försök igen',
    subscription_title: 'Prenumerationsplaner',
    free_tier: 'Gratis',
    pro_tier: 'Pro',
    business_tier: 'Business',
    monthly: 'Månadsvis',
    yearly: 'Årsvis',
    current_plan: 'Nuvarande plan',
    subscribe: 'Prenumerera',
    plan_feature_visibility: 'Ökad synlighet',
    plan_feature_priority: 'Prioriterad dispatch',
    plan_feature_analytics: 'Analyspanel',
    plan_feature_agency: 'Byråmodell',
    plan_feature_basic: 'Grundläggande listning',
    plan_feature_standard: 'Standard dispatch',
    save_percent: 'Spara',
    boost_title: 'Boosta synlighet',
    boost_desc: 'Visa högre i sökresultat',
    boost_active: 'Boost aktiv',
    boost_expires: 'Löper ut',
    boost_multiplier: '1.2x synlighetsmultiplikator',
    days: 'dagar',
    buy_boost: 'Köp boost',
    provider_detail: 'Leverantörsprofil',
    completed_jobs: 'Slutförda jobb',
    request_service: 'Begär tjänst',
    member_since: 'Medlem sedan',
    audit_logs: 'Revisionsloggar',
    no_logs: 'Inga loggar hittade',
    notif_enable: 'Aktivera push-aviseringar',
    notif_orders: 'Beställningsuppdateringar',
    notif_chat: 'Chattmeddelanden',
    notif_promo: 'Kampanjer',
    uploading: 'Laddar upp...',
    upload_success: 'Uppladdning lyckades',
    upload_error: 'Uppladdning misslyckades',
    dispatch_score: 'Dispatch-poäng',
    walking: 'Gång',
    driving: 'Körning',
    distance: 'Avstånd',
    duration: 'Varaktighet',
    km: 'km',
    min: 'min',
    commission_fee: 'Plattformsavgift',
    processing: 'Bearbetar betalning...',
    payment_success: 'Betalning lyckad',
    payment_failed: 'Betalning misslyckades',
    escrow_held: 'Medel hålls i escrow',
    export_requested: 'Dataexport begärd. Du kommer att få en nedladdningslänk.',
    delete_warning: 'Denna åtgärd kan inte ångras. Dina data raderas efter 30 dagar.',
    delete_confirm: 'Skriv DELETE för att bekräfta',
    account_deletion: 'Radera konto'
  }
};

/* ============================================
   STATE MANAGEMENT
   ============================================ */
const state = {
  lang: 'en',
  user: null,
  profile: null,
  providerProfile: null,
  categories: [],
  orders: [],
  currentOrder: null,
  currentQuotes: [],
  conversations: [],
  currentConversation: null,
  currentMessages: [],
  flags: {},
  route: 'login',
  routeParams: {},
  routeHistory: [],
  activeTab: 'home',
  loading: {},
  subscriptions: []
};

function t(key) {
  return (I18N[state.lang] && I18N[state.lang][key]) || I18N.en[key] || key;
}

function getCategoryName(cat) {
  if (!cat) return '';
  const key = `name_${state.lang}`;
  return cat[key] || cat.name_en || '';
}

/* ============================================
   SUPABASE CLIENT
   ============================================ */
let db = null;
try {
  if (window.supabase) {
    db = window.supabase.createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY);
  }
} catch(e) { console.error('Supabase init failed:', e); }

/* ============================================
   UTILITIES
   ============================================ */
function $(sel) { return document.querySelector(sel); }
function $$(sel) { return document.querySelectorAll(sel); }

function formatCurrency(amount, currency) {
  try {
    return new Intl.NumberFormat(state.lang === 'ar' ? 'ar-SA' : state.lang === 'no' ? 'nb-NO' : state.lang === 'sv' ? 'sv-SE' : 'en-US', {
      style: 'currency', currency: currency || 'SAR', minimumFractionDigits: 0, maximumFractionDigits: 2
    }).format(amount || 0);
  } catch { return `${amount} ${currency}`; }
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  const loc = state.lang === 'ar' ? 'ar-SA' : state.lang === 'no' ? 'nb-NO' : state.lang === 'sv' ? 'sv-SE' : 'en-US';
  return d.toLocaleDateString(loc, { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatTime(dateStr) {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function timeAgo(dateStr) {
  if (!dateStr) return '';
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return t('today');
  if (mins < 60) return `${mins}m ${t('ago')}`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ${t('ago')}`;
  const days = Math.floor(hrs / 24);
  if (days === 1) return t('yesterday');
  return `${days}d ${t('ago')}`;
}

const ICON_MAP = {'🔧':'wrench','⚡':'zap','🎨':'paintbrush','🧹':'sparkles','❄️':'snowflake','🪚':'hammer','📦':'truck','🌱':'leaf','🔌':'plug','🏠':'home'};
function catIconMap(emoji) { return ICON_MAP[emoji] || 'tool'; }
function icon(name, size = 20, cls = '') {
  return `<i data-lucide="${name}" style="width:${size}px;height:${size}px;display:inline-block;vertical-align:middle" class="${cls}"></i>`;
}
function refreshIcons() {
  if (window.lucide) window.lucide.createIcons();
}

function statusBadge(status) {
  const map = {
    pending: 'badge-warning', quoted: 'badge-info', confirmed: 'badge-primary',
    payment_pending: 'badge-warning', in_progress: 'badge-primary',
    completed: 'badge-success', closed: 'badge-neutral',
    cancelled: 'badge-danger', disputed: 'badge-danger'
  };
  return `<span class="badge ${map[status] || 'badge-neutral'}">${t('status_' + status)}</span>`;
}

function getInitials(name) {
  if (!name) return '?';
  return name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
}

function showToast(msg, type = 'success') {
  const el = document.createElement('div');
  el.className = `toast toast-${type}`;
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => el.remove(), 3000);
}

function setLoading(key, val) {
  state.loading[key] = val;
}

function debounce(fn, ms) {
  let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); };
}

/* ============================================
   ROUTER
   ============================================ */
function navigate(route, params = {}) {
  if (state.route !== route) {
    state.routeHistory.push({ route: state.route, params: state.routeParams });
  }
  state.route = route;
  state.routeParams = params;
  window.location.hash = route;
  render();
}

function goBack() {
  const prev = state.routeHistory.pop();
  if (prev) {
    state.route = prev.route;
    state.routeParams = prev.params;
    window.location.hash = prev.route;
    render();
  } else {
    navigate(getDefaultRoute());
  }
}

function getDefaultRoute() {
  if (!state.user) return 'login';
  const role = state.profile?.role;
  if (role === 'admin' || role === 'superadmin') return 'admin-dashboard';
  if (role === 'provider') return 'provider-dashboard';
  return 'home';
}
